from __future__ import annotations

from enum import Enum, StrEnum


class ErrorCode(StrEnum):
    """
    Перечисление внутренних кодов ошибок приложения.
    """

    # Base
    BASE_ERROR = "BASE_ERROR"

    # File & Storage
    FILE_PROCESSING_ERROR = "FILE_PROCESSING_ERROR"
    FILE_NOT_FOUND_ERROR = "FILE_NOT_FOUND_ERROR"
    ZIP_EXTRACTION_ERROR = "ZIP_EXTRACTION_ERROR"
    FILE_NOT_ZIP_ERROR = "FILE_NOT_ZIP_ERROR"
    FILE_SIZE_ERROR = "FILE_SIZE_ERROR"
    CSV_FILE_PARSING_ERROR = "CSV_FILE_PARSING_ERROR"
    JSON_FILE_PARSING_ERROR = "JSON_FILE_PARSING_ERROR"
    GZIP_EXTRACTION_ERROR = "GZIP_EXTRACTION_ERROR"
    FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    EMPTY_DATA_ERROR = "EMPTY_DATA_ERROR"

    # Database
    ERROR_WORKING_WITH_DB = "ERROR_WORKING_WITH_DB"
    ERROR_LOADING_DATA_TO_DB = "ERROR_LOADING_DATA_TO_DB"
    DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR"
    DB_COMMUNICATION_ERROR = "DB_COMMUNICATION_ERROR"
    DB_INVALID_COMMUNICATION_TYPE = "DB_INVALID_COMMUNICATION_TYPE"
    DB_INVALID_COMMUNICATION_VALUE = "DB_INVALID_COMMUNICATION_VALUE"

    # Data Processing
    DATA_PROCESSING_ERROR = "DATA_PROCESSING_ERROR"
    PRICE_PROCESSING_ERROR = "PRICE_PROCESSING_ERROR"
    EMAIL_FETCH_ERROR = "EMAIL_FETCH_ERROR"
    DRIVE_API_ERROR = "DRIVE_API_ERROR"
    EXCEL_PROCESSING_ERROR = "EXCEL_PROCESSING_ERROR"
    SUPPLIER_DATA_ERROR = "SUPPLIER_DATA_ERROR"

    # Network & API
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DOWNLOAD_ERROR = "DOWNLOAD_ERROR"
    API_ERROR = "API_ERROR"

    # Settings
    SETTINGS_ERROR = "SETTINGS_ERROR"
    INVALID_SETTINGS_VALUE_ERROR = "INVALID_SETTINGS_VALUE_ERROR"
    SETTINGS_LOAD_ERROR = "SETTINGS_LOAD_ERROR"
    PRODUCTION_SETTINGS_ERROR = "PRODUCTION_SETTINGS_ERROR"

    # redis
    REDIS_CLIENT_ERROR = "REDIS_CLIENT_ERROR"
    REDIS_CONNECTION_ERROR = "REDIS_CONNECTION_ERROR"
    REDIS_AUTH_ERROR = "REDIS_AUTH_ERROR"
    REDIS_NOT_INIT_ERROR = "REDIS_NOT_INIT_ERROR"
    REDIS_TIME_OUT_ERROR = "REDIS_TIME_OUT_ERROR"

    # Entity
    ENTITY_ERROR = "ENTITY_ERROR"
    SCHEMA_NOT_FOUND_ERROR = "SCHEMA_NOT_FOUND_ERROR"
    USER_ENTITY_ERROR = "USER_ENTITY_ERROR"
    USER_NOT_FOUND_ERROR = "USER_NOT_FOUND_ERROR"

    # Schemas
    SCHEMA_ERROR = "SCHEMA_ERROR"
    COMPARISON_ERROR = "COMPARISON_ERROR"
    FIELD_COMPARISON_ERROR = "FIELD_COMPARISON_ERROR"
    PAGINATION_ERROR = "PAGINATION_ERROR"
    SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR"
    NEGATIVE_VALUE_ERROR = "NEGATIVE_VALUE_ERROR"

    # Bitrix24
    BITRIX24_ERROR = "BITRIX24_ERROR"
    BITRIX_VALIDATION_ERROR = "BITRIX_VALIDATION_ERROR"
    BITRIX_PARSE_ERROR = "BITRIX_PARSE_ERROR"
    BITRIX_TYPE_ERROR = "BITRIX_TYPE_ERROR"
    BITRIX_AUTH_ERROR = "BITRIX_AUTH_ERROR"
    BITRIX_API_ERROR = "BITRIX_API_ERROR"

    # Bitrix dependencies container
    BITRIX_CONTAINER_ERROR = "BITRIX_CONTAINER_ERROR"
    BITRIX_CONTAINER_INIT_ERROR = "BITRIX_CONTAINER_INIT_ERROR"
    BITRIX_CONTAINER_ENTITY_INIT_ERROR = "BITRIX_CONTAINER_ENTITY_INIT_ERROR"

    # Token
    CIPHER_ERROR = "CIPHER_ERROR"
    CIPHER_ENCRYPTION_ERROR = "CIPHER_ENCRYPTION_ERROR"
    CIPHER_DECRYPTION_ERROR = "CIPHER_DECRYPTION_ERROR"
    CIPHER_INVALID_TOKEN = "CIPHER_INVALID_TOKEN"  # noqa: S105
    CIPHER_CONFIGURATION_ERROR = "CIPHER_CONFIGURATION_ERROR"
    TOKEN_STORAGE_ERROR = "TOKEN_STORAGE_ERROR"  # noqa: S105
    STORAGE_CONNECTION_ERROR = "STORAGE_CONNECTION_ERROR"
    TOKEN_SAVE_ERROR = "TOKEN_SAVE_ERROR"  # noqa: S105
    TOKEN_DELETE_ERROR = "TOKEN_DELETE_ERROR"  # noqa: S105
    INVALID_TOKEN_TYPE_ERROR = "INVALID_TOKEN_TYPE_ERROR"  # noqa: S105
    TOKEN_STORAGE_INIT_ERROR = "TOKEN_STORAGE_INIT_ERROR"  # noqa: S105

    # Site sync
    CONFLICT_ERROR = "CONFLICT_ERROR"
    CYCLIC_CALL_ERROR = "CYCLIC_CALL_ERROR"
    DEAL_PROCESSING_ERROR = "DEAL_PROCESSING_ERROR"
    DEAL_NOT_FOUND_ERROR = "DEAL_NOT_FOUND_ERROR"
    DEAL_NOT_IN_MAIN_FUNNEL_ERROR = "DEAL_NOT_IN_MAIN_FUNNEL_ERROR"
    DEAL_SYNC_ERROR = "DEAL_SYNC_ERROR"
    INVALID_DEAL_STATUS_ERROR = "INVALID_DEAL_STATUS_ERROR"
    INVALID_DEAL_STATE_ERROR = "INVALID_DEAL_STATE_ERROR"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    DOCUMENT_PROCESSING_ERROR = "DOCUMENT_PROCESSING_ERROR"
    COMPANY_CLIENT_NOT_INITIALIZED_ERROR = "COMPANY_CLIENT_NOT_INITIALIZED_ERROR"
    WEBHOOK_VALIDATION_ERROR = "WEBHOOK_VALIDATION_ERROR"
    WEBHOOK_SECURITY_ERROR = "WEBHOOK_SECURITY_ERROR"
    LOCK_ACQUISITION_ERROR = "LOCK_ACQUISITION_ERROR"
    MAX_RETRIES_EXCEEDED_ERROR = "MAX_RETRIES_EXCEEDED_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    ENTITY_NOT_FOUND_ERROR = "ENTITY_NOT_FOUND_ERROR"
    DATABASE_EXCEPTION = "DATABASE_EXCEPTION"
    SITE_REQUEST_PROCESSING_ERROR = "SITE_REQUEST_PROCESSING_ERROR"
    MANAGER_NOT_FOUND_ERROR = "MANAGER_NOT_FOUND_ERROR"
    DEAL_CREATION_ERROR = "DEAL_CREATION_ERROR"
    CONTACT_CREATION_ERROR = "CONTACT_CREATION_ERROR"
    PRODUCT_NOT_FOUND_ERROR = "PRODUCT_NOT_FOUND_ERROR"
    FILE_DOWNLOAD_ERROR = "FILE_DOWNLOAD_ERROR"
    PRODUCT_TRANSFORMATION_ERROR = "PRODUCT_TRANSFORMATION_ERROR"


class ErrorMessages(Enum):
    """Стандартизированные сообщения об ошибках с кодами."""

    NOT_ZIP = ("FILE_NOT_ZIP", "Файл должен быть в формате ZIP")
    INVALID_ZIP = ("INVALID_ZIP", "Файл не является валидным ZIP архивом")
    SIZE_LIMIT = ("FILE_TOO_LARGE", "Размер файла превышает лимит")
    SAVE_FAILED = ("SAVE_FAILED", "Ошибка при сохранении файла")
    VALIDATION_FAILED = (
        "VALIDATION_FAILED",
        "Ошибка при проверке ZIP архива",
    )
    CSV_NOT_FOUND = ("CSV_NOT_FOUND", "CSV файл не найден внутри архива")
    UNZIP_FAILED = ("ZIP_EXTRACTION_ERROR", "Не удалось распаковать архив")

    def __init__(self, code: str, message: str) -> None:
        self._code = code
        self._message = message

    @property
    def code(self) -> str:
        """Код ошибки."""
        return self._code

    @property
    def message(self) -> str:
        """Текстовое сообщение об ошибке."""
        return self._message
