from common.exceptions.app_token import (
    CipherConfigurationError as InvalidEncryptionKeyError,
    CipherDecryptionError as TokenDecryptionError,
    CipherEncryptionError as TokenEncryptionError,
    CipherError as TokenCipherError,
    StorageConnectionError as TokenStorageConnectionError,
    TokenStorageError,
    TokenStorageInitError,
)
from common.exceptions.base import BaseAppException
from common.exceptions.database import DatabaseConnectionError
from common.exceptions.site import (
    BitrixApiError,
    BitrixAuthError,
    CompanyClientNotInitializedError,
    ConflictException,
    ContactCreationError,
    CyclicCallException,
    DatabaseException,
    DealCreationError,
    DealNotFoundError,
    DealNotInMainFunnelError,
    DealProcessingError,
    DealSyncError,
    DocumentProcessingError,
    EntityNotFoundException,
    ExternalServiceError,
    FileDownloadError,
    InvalidDealStateError,
    InvalidDealStatusError,
    LockAcquisitionError,
    ManagerNotFoundError,
    MaxRetriesExceededError,
    ProductNotFoundError,
    ProductTransformationError,
    SiteRequestProcessingError,
    ValidationError,
    WebhookSecurityError,
    WebhookValidationError,
    create_bitrix_api_error_from_response,
    should_retry_operation,
)


TokenNotFoundError = TokenStorageInitError

__all__ = [
    "BaseAppException",
    "BitrixApiError",
    "BitrixAuthError",
    "CompanyClientNotInitializedError",
    "ConflictException",
    "ContactCreationError",
    "CyclicCallException",
    "DatabaseConnectionError",
    "DatabaseException",
    "DealCreationError",
    "DealNotFoundError",
    "DealNotInMainFunnelError",
    "DealProcessingError",
    "DealSyncError",
    "DocumentProcessingError",
    "EntityNotFoundException",
    "ExternalServiceError",
    "FileDownloadError",
    "InvalidDealStateError",
    "InvalidDealStatusError",
    "InvalidEncryptionKeyError",
    "LockAcquisitionError",
    "ManagerNotFoundError",
    "MaxRetriesExceededError",
    "ProductNotFoundError",
    "ProductTransformationError",
    "SiteRequestProcessingError",
    "TokenCipherError",
    "TokenDecryptionError",
    "TokenEncryptionError",
    "TokenNotFoundError",
    "TokenStorageConnectionError",
    "TokenStorageError",
    "ValidationError",
    "WebhookSecurityError",
    "WebhookValidationError",
    "create_bitrix_api_error_from_response",
    "should_retry_operation",
]
