"""Initial

Revision ID: 4fa44b0d4d4b
Revises:
Create Date: 2026-07-02 14:04:26.837345

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4fa44b0d4d4b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier_clothing_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("subcategory", sa.String(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("product_summary", sa.String(), nullable=False),
        sa.Column("size", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("supplier_code", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "code",
            "supplier_id",
            name="uq_supplier_clothing_codes_code_supplier",
        ),
    )
    op.create_index(
        "idx_supplier_clothing_codes_name",
        "supplier_clothing_codes",
        ["name"],
        unique=False,
    )
    op.create_index(
        "idx_supplier_clothing_codes_supplier_code",
        "supplier_clothing_codes",
        ["supplier_id", "code"],
        unique=False,
    )
    op.create_table(
        "supplier_price",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("subcategory", sa.String(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("product_summary", sa.String(), nullable=False),
        sa.Column("size", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "code", "supplier_id", name="uq_supplier_price_code_supplier"
        ),
    )
    op.create_index(
        "idx_supplier_price_name", "supplier_price", ["name"], unique=False
    )
    op.create_index(
        "idx_supplier_price_supplier_code",
        "supplier_price",
        ["supplier_id", "code"],
        unique=False,
    )
    op.create_table(
        "supplier_product_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("subcategory", sa.String(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "code",
            "supplier_id",
            name="uq_supplier_product_codes_code_supplier",
        ),
    )
    op.create_index(
        "idx_supplier_product_codes_name",
        "supplier_product_codes",
        ["name"],
        unique=False,
    )
    op.create_index(
        "idx_supplier_product_codes_supplier_code",
        "supplier_product_codes",
        ["supplier_id", "code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_supplier_product_codes_supplier_code",
        table_name="supplier_product_codes",
    )
    op.drop_index(
        "idx_supplier_product_codes_name", table_name="supplier_product_codes"
    )
    op.drop_table("supplier_product_codes")
    op.drop_index(
        "idx_supplier_price_supplier_code", table_name="supplier_price"
    )
    op.drop_index("idx_supplier_price_name", table_name="supplier_price")
    op.drop_table("supplier_price")
    op.drop_index(
        "idx_supplier_clothing_codes_supplier_code",
        table_name="supplier_clothing_codes",
    )
    op.drop_index(
        "idx_supplier_clothing_codes_name",
        table_name="supplier_clothing_codes",
    )
    op.drop_table("supplier_clothing_codes")
    # ### end Alembic commands ###
